name: notivocab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_native_timezone_updated_gradle: ^2.0.3
  flutter_app_badger: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true
  assets:
    - asset/notivocab-icon.png
    - asset/ngsl_v1_2.db

  fonts:   
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
        - asset: fonts/NotoSansJP-Medium.ttf
        - asset: fonts/NotoSansJP-Bold.ttf
        - asset: fonts/NotoSansJP-Black.ttf
        - asset: fonts/NotoSansJP-Thin.ttf
        - asset: fonts/NotoSansJP-Light.ttf
        - asset: fonts/NotoSansJP-ExtraLight.ttf
        - asset: fonts/NotoSansJP-SemiBold.ttf
        - asset: fonts/NotoSansJP-ExtraBold.ttf

    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
